name: Build, SonarCloud Analysis, CodeQL,  and JFrog Upload Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Analysis and JFrog Upload
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for Sonar analysis

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Step 4: Run Maven Build
      - name: Build Project
        run: |
          mvn clean verify

      # Step 5: SonarCloud Scan
      - name: Set executable permissions
        run: chmod +x ./scripts/run-sonarqube-analysis.sh

      - name: Run SonarQube Analysis
        run: ./scripts/run-sonarqube-analysis.sh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 6: Install JFrog CLI
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/

      # Step 7: Configure JFrog CLI
      - name: Configure JFrog CLI
        run: |
          jfrog config add my-server \
            --artifactory-url ${{ secrets.JFROG_URL }} \
            --user ${{ secrets.JFROG_USERNAME }} \
            --password ${{ secrets.JFROG_PASSWORD }}

      # Step 8: Upload Build Artifacts to JFrog
      # Uncomment the following if you want to upload artifacts to JFrog
      # - name: Upload Build Artifacts to JFrog
      #   run: |
      #     jfrog rt upload "target/*.jar" "githubaction/githubaction/"

      # Step 9: Generate code coverage report
      - name: Generate code coverage report
        run: |
          mvn jacoco:report

      # Step 10: Publish code coverage result
      - name: Publish code coverage result
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: target/site/jacoco/index.html

  # **New Job for CodeQL Analysis**
  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    needs: sonarqube  # This job depends on the completion of the SonarQube job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for CodeQL analysis

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Build the project (important for Java analysis)
      - name: Build Java Project
        run: mvn clean compile

      # Step 4: Set up CodeQL
      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'  # Specify the language for analysis

      # Step 5: Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
     
  notify:
    runs-on: ubuntu-latest
    needs: [sonarqube, codeql]  # This job depends on both SonarQube and CodeQL jobs
    if: always()  # Run this job regardless of the result of previous jobs

    steps:
      # Step 1: Send notification to Slack using Incoming Webhook
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "GITHUB HOSTED SonarQube and CodeQL analysis completed with status: ${{ needs.sonarqube.result }} and ${{ needs.codeql.result }}."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
